### ISSUE TITLE
replace ENV issue

### ISSUE THREAD

**Issue by sheriff91** [jlengstorf/learn-rollup#1]
Running this command:
`NODE_ENV=production ./node_modules/.bin/rollup -c`
results in the following error:

```
NODE_ENV=production : The term 'NODE_ENV=production' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ NODE_ENV=production ./node_modules/.bin/rollup -c
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (NODE_ENV=production:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Not sure why - I have all the dependencies etc in there.

**Comment by jlengstorf** [comment]
If I'm guessing correctly, you're on Windows, right?

According to [this discussion](http://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman), it looks like you'll need a slightly different command:

``` sh
SET NODE_ENV=production ./node_modules/.bin/rollup -c
```

I'll add a note to the article before closing this.
