### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by saun4app** [jlengstorf/learn-rollup#11]
@jlengstorf, thank you very much for creating this great `rollup` tutorial. 

I did not find a way to resolve this error: `Uncaught ReferenceError: d3` is not defined, using `rollup-plugin-node-resolve` and `rollup-plugin-commonjs` as instructed in your tutorial for avoiding the same error with `debug`. 

I would appreciate any pointers to get around this error (https://github.com/saun4app/hello-d3-es6-rollup).

Thank you very much.

**Comment by jlengstorf** [comment]
This issue doesn't have anything to do with this repo. I did spot your problem, though, so I sent a [pull request to the repo](https://github.com/saun4app/hello-d3-es6-rollup/pull/1).

**Comment by saun4app** [comment]
@jlengstorf, thank you for help and prompt action.  Sorry, I did not mean to imply that the error caused by `learn-rollup`.

**Comment by jlengstorf** [comment]
No worries. Happy to help. :)
