### ISSUE TITLE
How to require asset file?

### ISSUE THREAD

**Issue by gaterking** [jlengstorf/learn-rollup#15]
Using webpack, we can use file-loader to require a file(json/png/jpg) in js file, then webpack will publish the file to dist.
`let zhCNJson = require('file?name=i18n/zh-CN.[hash:8].[ext]!../../i18n/zh-CN.json');`
Can rollup do it?

**Comment by jlengstorf** [comment]
I haven't tried this specific use of Rollup, so this is probably a better question for the [official Rollup repo](https://github.com/rollup/rollup). I don't _think_ it's supported, though.

I've worked around this using npm scripts and a package like [copyfiles](https://github.com/calvinmetcalf/copyfiles):

``` json
  "scripts": {
    "build": "npm run copy && npm run bundle",
    "bundle": "NODE_ENV=production rollup -c",
    "copy": "copyfiles -f static/**/* dist"
  },
```

That's a simplified excerpt from the `package.json` of one of my projects. It basically copies the contents of the `static` dir to the `dist` dir.

So the short answer (I think) is, "No."

But the longer answer is, "That's not really what Rollup is for, and it's really easy to get that functionality without putting it into Rollup."

**Comment by gaterking** [comment]
@jlengstorf With webpack, we packs any anything from one entry. Maybe Rollup is another pack method. 
Somethimes we will organization our code as separate components. Every component has it own css、js、html and resource file. The component will be used by many another page html or js. But they not need to pack component's every thing manually. 
Do you think this is the best usage for this feature?

**Comment by jlengstorf** [comment]
I think an advanced build like that probably merits webpack 2. They're using Rollup under the hood, so you get the benefits of smaller bundles plus the extra stuff you're looking for. 

Good luck!

**Comment by gaterking** [comment]
OK, Thanks.
