### ISSUE TITLE
Use & instead of npm-run-all

### ISSUE THREAD

**Issue by ArthurClemens** [jlengstorf/learn-rollup#18]
There's no need to install package `npm-run-all` when all it does is run 2 scripts in parallel. Simply write in package.json:

```
"watch": "npm run reload & npm run dev"
```

**Comment by jlengstorf** [comment]
@ArthurClemens That... is an excellent point. For the sake of consistency in the video I'm going to leave it unchanged, but I'll definitely make sure not to add unnecessary dependencies in future videos. Thanks!
