### ISSUE TITLE
Minor bug in comment about debug

### ISSUE THREAD

**Issue by helenb** [jlengstorf/learn-rollup#24]
In your code example you have the following:

```
// The logger should only be disabled if we’re not in production.
if (ENV !== 'production') {

  // Enable the logger.
  debug.enable('*');
  log('Logging is enabled!');
} else {
  debug.disable();
}
```

I think if I've understood correctly that the comment should read 'The logger should only be enabled if we're not in production'

**Comment by jlengstorf** [comment]
You're absolutely correct. This was fixed in #22, and is reflected in the code on the repo now (https://github.com/jlengstorf/learn-rollup/blob/master/src/scripts/main.js#L12). Thanks!
