### ISSUE TITLE
Can't preview in http://127.0.0.1:35729/

### ISSUE THREAD

**Issue by showzyl** [jlengstorf/learn-rollup#25]
git clone https://github.com/jlengstorf/learn-rollup/
cd learn-rollup
yarn install
npm run watch
bundle is well, but can't preview in http://127.0.0.1:35729/
my node version is  v7.6.0

**Comment by showzyl** [comment]
i was opened index.html preview in the browser, it worked.
but how to add multi page entry?

**Comment by jlengstorf** [comment]
Hi, @showzyl — I'm not sure I understand the question. Can you explain what you're trying to do?

Thanks!

**Comment by showzyl** [comment]
hi, @jlengstorf  i want a dev-server like webpack-dev-server. but the demo didn't provide.😀

**Comment by showzyl** [comment]
i run `npm run reload `
http://127.0.0.1:35729/   has nothing.

**Comment by jlengstorf** [comment]
Hey, @showzyl — I have a walkthrough for setting up a dev server with LiveReload in the second part of the series: https://code.lengstorf.com/learn-rollup-css/#livereload

I'm going to close this. Good luck!
