### ISSUE TITLE
Update post for moduleName with IIFE

### ISSUE THREAD

**Issue by ghost** [jlengstorf/learn-rollup#26]
rollup version 0.41.4

`🚨 You must supply options.moduleName for IIFE bundles`

Example module name:
http://rollupjs.org/#using-rollup-with-gulp. Without it will not transpile.

**Comment by jlengstorf** [comment]
Hey, @jhabdas — I think this is Gulp-specific. I can't find anything in the docs or changelog that suggests otherwise. Did you run into this in a non-Gulp setup?

**Comment by ghost** [comment]
Yes, bare setup. https://github.com/jhabdas/fetch-inject

**Comment by jlengstorf** [comment]
@jhabdas I think this has changed. I just pulled Rollup v0.41.6 and used the following config:

``` js
export default {
  entry: 'src/index.js',
  dest: 'build/js/bundle.js',
  format: 'iife',
  sourceMap: 'inline',
}
```

This successfully bundled two small modules. The docs _do_ say that `moduleName` is required for UMD format, though.

I'm going to close this, but let me know if there's something else you've found that could affect IIFE generation.

**Comment by ghost** [comment]
FYI - https://github.com/rollup/rollup/issues/1157#issuecomment-268284551. TL;DR, if your module exports, then you need to give it a name. Thanks again for your attention and help. Love your website and great article!

**Comment by jlengstorf** [comment]
@jhabdas This is really helpful — thanks for digging up that comment and clarifying!
