### ISSUE TITLE
rollup is compatible with IE8+？

### ISSUE THREAD

**Issue by tedyhy** [jlengstorf/learn-rollup#27]
hi，I want to understand that rollup.js is compatible with IE8+？

**Comment by jlengstorf** [comment]
Hi, there.

Rollup is not executed by the browser, so you'll have no problems with Rollup itself. To make sure everything is working in IE8+, you'll most likely need to configure the [Babel polyfill](https://babeljs.io/docs/usage/polyfill/).

Good luck!
