### ISSUE TITLE
url changes for tutorial pointing to repo/repo issues

### ISSUE THREAD

**Issue by ChipNowacek** [jlengstorf/learn-rollup#33]
In the "Questions? Ideas? Spotted a Bug?" section at the bottom of [Rollup.js Tutorial, Part 2](https://code.lengstorf.com/learn-rollup-css/), the links to https://github.com/jlengstorf/learn-rollup-js/ give a 404. I think it's just the "-js" that's giving the grief.

Great tutorial. Thanks.

**Comment by jlengstorf** [comment]
Thanks — fixed!
