### ISSUE TITLE
js test

### ISSUE THREAD

**Issue by idavollen** [jlengstorf/learn-rollup#36]
Hi,

I tried to run js test with your code by adding a array.spec.js under app-root/test:
import addArray from '../src/modules/mod2';
```
describe('Object History API Testing', function() {
  
    it('Updating history should change history', function() {
      var res = addArray([1, 2, 3, 4]);
      expect(res).toBe(10);
    });

});
```

and change a bit in package.json

    "test": "cross-env BABEL_ENV=commonjs jest"
added corresponding dependencies, however, it failed with such an error message:
SyntaxError: Unexpected token import

Do you have any idea on it? Or can you add some js test code for the purpose as example?

Thanks in advance!

**Comment by jlengstorf** [comment]
@idavollen I just added a new branch called `alt-config/jest` with Jest configuration and tests for the two modules. Check out [the diff](https://github.com/jlengstorf/learn-rollup/commit/d30649763b3bf51d9f4675e943b4469f9156c103) to see how I approached configuration — there's a little bit of env-specific `.babelrc` stuff that's required.

**Comment by idavollen** [comment]
@jlengstorf Thanks for your great work!
