### ISSUE TITLE
React support

### ISSUE THREAD

**Issue by ghost** [jlengstorf/learn-rollup#4]
I've struggled trying to make react work with rollup.
If you find it useful, [here](https://github.com/wesleycoder/learn-rollup/commit/4f5403b1d3f3ddbd58e5e14f812a6c855e786f0a) is how I solved it.

It would be useful for others if you put a tip at the end of your post. Or you could push it in a branch here for reference.

**Comment by jlengstorf** [comment]
Thanks for putting this up — I'll add a note to the post. Out of curiosity, did you try Babel's React preset? That could avoid the JSX stuff, which would make the setup even simpler.

**Comment by ghost** [comment]
I have tried, but it doesn't seem to work out of the box, I'll give it
another try and make another commit with the result and let you know what
happens.

**Comment by jlengstorf** [comment]
@wesleycoder how would you feel about sending this in as a pull request? I'll put it on another branch and link to it from the README as a variation on the initial repo. I have #5 open right now to add an Express server, so we'd have two setup variations to start.

**Comment by ghost** [comment]
Sure, I'll send the PR soon.

**Comment by ghost** [comment]
May I send the PR to the `master` branch or will you create another branch in which I'll send the PR?
It is [ready to send](https://github.com/wesleycoder/learn-rollup/tree/feature/react-support).

**Comment by jlengstorf** [comment]
@wesleycoder I just created a branch called [alt-config/react](/jlengstorf/learn-rollup/tree/alt-config/react). Can you send the PR against that one?

Thanks!
