### ISSUE TITLE
hi! thanks alot for the great tutorial! i am using livereload and it works, opening the index html directly in chrome. But when loading a local csv (d3.csv) i get cross origin problems. Is there a way to fix this? best malte

### ISSUE THREAD

**Issue by schwrrring** [jlengstorf/learn-rollup#40]
Please note that this is not a support forum for Rollup. If your issue is not directly related to the tutorial code, this is NOT the right place to open an issue.

If you are getting Rollup errors with a particular module, try opening an issue on that module's repo first.

If you are getting Rollup errors with multiple modules, open an issue on the Rollup repo: https://github.com/rollup/rollup

Thanks!

**Comment by jlengstorf** [comment]
Hi, @schwrrring — this isn't a support forum, so I can't help with non-tutorial code, but I'd recommend opening an issue with the module you're using to import the CSV files.

Good luck!
