### ISSUE TITLE
Get pug loader to work with rollup

### ISSUE THREAD

**Issue by nickngqs** [jlengstorf/learn-rollup#41]
Everything is great with the tutorial. But I'm wondering if you can add another one regarding on how to get pug to work with rollup, i've tried all solutions using both rollup-plugin-pug and rollup-plugin-pug-html.

Both doesn't seem to work. Just thought you can expand on that :D

**Comment by jlengstorf** [comment]
I haven't tried those plugins, but I'd open an issue in the plugin repos themselves — they'll probably have more information than I do. :)
