### ISSUE TITLE
Using rollup with multiple inputs

### ISSUE THREAD

**Issue by portfolio-systems** [jlengstorf/learn-rollup#43]
Hi

Thanks for the tutorials, couple of points, first a small problem and second a request

1. rollup -w fails quite frequently with some misc garbage at the ens of bundle.js (duplicated bits of the 'real' content). Stopping the watcher and restarting fixes it but it renders the watch process effectively useless ???

2. I am unable to figure out how to use rollup in a *real* project (ie not a toy piece of code) that would involve tens or hundreds of html forms each with its own 'bundle.js'. How do you configure all this ??

Regards

Ron Yuen

**Comment by jlengstorf** [comment]
Hi, Ron.

Regarding your first question, I'd open an issue on the Rollup repo with more details.

Regarding the second, I'm not sure what your architecture looks like, but this sounds like it might be a more complex project than Rollup is intended to manage. You may want to look into Webpack instead.

Good luck!
