### ISSUE TITLE
Babel's "Unexpected token error

### ISSUE THREAD

**Issue by alejandroiglesias** [jlengstorf/learn-rollup#44]
Please note that this is not a support forum for Rollup. If your issue is not directly related to the tutorial code, this is NOT the right place to open an issue.

If you are getting Rollup errors with a particular module, try opening an issue on that module's repo first.

If you are getting Rollup errors with multiple modules, open an issue on the Rollup repo: https://github.com/rollup/rollup

Thanks!

**Comment by jlengstorf** [comment]
This is a duplicate of #45
