### ISSUE TITLE
Including PostCss results in syntax error

### ISSUE THREAD

**Issue by SumNeuron** [jlengstorf/learn-rollup#49]
I was going through the tutorial in a more belabored way (not using your git repo, but copying all by hand). Went through part 1 no problems (except a missing dependency of bable-core). 

When I try to include postcss i get a syntax error and I do have it in the packages.json file.

**Comment by jlengstorf** [comment]
Hi, @SumNeuron — if there's a syntax error, I'd do a comparison between the tutorial code and your code to see what's different. If your code is different from the tutorial, I'd recommend posting an issue on the Babel or PostCSS repo with the specific error and your source code.

Good luck!
