### ISSUE TITLE
postcss-cssnext is deprecated

### ISSUE THREAD

**Issue by cwilling** [jlengstorf/learn-rollup#50]
I've been using postcss-cssnext in my project as described in your tutorial for some time and it's been working really well - thanks for that!

Today I rebuilt all my node_modules tree and there was a message that
```
'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
```
I tried the migration instructions there without success.

Are you considering updating the tutorial to use postcss-preset-env at all?

**Comment by jlengstorf** [comment]
@cwilling hey there — honestly I probably won't update it in the tutorial because I think it's pretty out-of-date with other Rollup features as well. 😕 

If you'd like to submit a PR with a fix, I'm happy to accept it, though!
