### ISSUE TITLE
CSS is not insert into Head after building

### ISSUE THREAD

**Issue by Sara2009** [jlengstorf/learn-rollup#51]
I clone the project and npm install the package. Then npm run build. The css is not bundled into the head of bulid/index.html but into the js/main.min.js using __$styleInject

**Comment by jlengstorf** [comment]
Hi, @Sara2009! This repo is pretty far out of date, so I'm not sure if it's still a good representation of how Rollup should be used. My recommendation would be to check the Rollup docs for updated tutorials to make sure you're getting the best information.

I'm going to close this issue, but please feel free to ask additional questions!
