### ISSUE TITLE
LiveReload plugin

### ISSUE THREAD

**Issue by thgh** [jlengstorf/learn-rollup#6]
Just wanted to let you know that I made this plugin after reading your tutorial:
https://github.com/thgh/rollup-plugin-livereload

It might make the livereload chapter somewhat easier 😃

**Comment by jlengstorf** [comment]
Hey, @thgh — thanks for sharing! I've started adding [alternative configurations](https://github.com/jlengstorf/learn-rollup#alternative-configurations) to the project README, so if you'd like to submit a PR with this plugin replacing the existing watch/reload setup, we can add it to the list.

You can send the PR against `master` — I'll create a new branch for it before I merge it in.

Thanks!
